'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
require('../dist/core.js');require('../dist/maps.js');require('../dist/network.js');const C=globalThis.CA;
function arena(mode='TEAM',map=C.MAPS[0]){const a=new C.Arena();a.start(mode,map);a.updateAI=()=>{};return a;}
function advance(a,seconds,input={}){for(let t=0;t<seconds-1e-8;t+=.025)a.tick(Math.min(.025,seconds-t),input);}
function openMap(){return {...C.MAPS[0],grid:Array.from({length:27},(_,y)=>Array.from({length:30},(_,x)=>!x||!y||x===29||y===26?1:0))};}
function shootingArena(){const a=arena('TEAM',openMap());a.checkRules=()=>{};const p=a.player(),t=a.entities[5];p.x=224;p.y=224;p.angle=0;t.x=340;t.y=224;for(const e of a.entities)if(e!==p&&e!==t)e.alive=false;return {a,p,t};}

test('all four authored maps have reachable, non-overlapping distributed spawn layouts',()=>{
  assert.equal(C.MAPS.length,4);for(const m of C.MAPS){assert.equal(m.width,30);assert.equal(m.height,27);assert.equal(m.ffa.length,10);assert.equal(m.hunters.length,9);assert.equal(m.points.length,3);
    const points=[...m.ffa,...m.spawns.BLUE,...m.spawns.RED,...m.points,...m.pickups];for(const p of points){assert.ok(C.canStand(m,p.x,p.y,19),m.name);if(C.dist(points[0],p)>64)assert.ok(C.pathfind(m,points[0],p).length,m.name);}
    for(let i=0;i<10;i++)for(let j=i+1;j<10;j++)assert.ok(C.dist(m.ffa[i],m.ffa[j])>80);
  }
});
test('every local mode creates exactly 10 combatants with the correct teams',()=>{
  for(const mode of Object.keys(C.MODES)){const a=arena(mode);assert.equal(a.entities.length,10);if(mode==='BOSS'){assert.equal(a.player().maxHp,2000);assert.equal(a.player().maxShield,1000);assert.equal(a.entities.filter(e=>e.team==='HUNTERS').length,9);}else if(!C.MODES[mode].ffa){assert.equal(a.entities.filter(e=>e.team==='BLUE').length,5);assert.equal(a.entities.filter(e=>e.team==='RED').length,5);}else assert.deepEqual(a.entities.slice(1).map(e=>e.name),Array.from({length:9},(_,i)=>'SOLO-'+(i+2)));}
});
test('FFA enemy decisions ignore all team labels and exclude self',()=>{for(const mode of['SOLO','INFINITY']){const a=arena(mode);for(const e of a.entities)e.team='BLUE';for(const e of a.entities){assert.equal(C.enemy(e,e,mode),false);for(const t of a.entities)if(e!==t)assert.equal(C.enemy(e,t,mode),true);}}});
test('TEAM and SOLO do not respawn a eliminated player in the same round',()=>{for(const mode of ['TEAM','SOLO']){const a=arena(mode),p=a.player();a.damage(p,1000,a.entities[5]);advance(a,9);assert.equal(p.alive,false);assert.equal(a.round,1);assert.equal(a.state,'PLAYING');assert.ok(a.spectatorId);}});
test('TEAM seven wins moves through ROUND_END and MATCH_END, returns to lobby, and resets all cheats',()=>{
  const a=arena(),id=a.map.id;a.cheats={aim:true,esp:true,noRecoil:true};for(let round=1;round<=7;round++){a.finishRound('BLUE','test');assert.equal(a.state,'ROUND_END');assert.equal(a.score.BLUE,round);advance(a,3.6);assert.equal(a.map.id,id);if(round<7)assert.equal(a.state,'PLAYING');}
  assert.equal(a.state,'MATCH_END');assert.deepEqual(a.cheats,{aim:false,esp:false,noRecoil:false});advance(a,7.1);assert.equal(a.state,'LOBBY');
});
test('TEAM timeout compares survivor count before combined HP and shield',()=>{const a=arena();a.entities[5].alive=false;a.entities.filter(e=>e.team==='BLUE').forEach(e=>{e.hp=1;e.shield=0;});a.roundEndsAt=0;a.checkRules();assert.equal(a.result.winner,'BLUE');});
test('TEAM timeout uses HP + shield, then draws on an exact tie',()=>{const a=arena();a.entities[0].shield=49;a.roundEndsAt=0;a.checkRules();assert.equal(a.result.winner,'RED');const b=arena();b.roundEndsAt=0;b.checkRules();assert.equal(b.result.draw,true);assert.equal(b.score.BLUE+b.score.RED,0);advance(b,3.6);assert.equal(b.state,'PLAYING');});
test('SOLO last survivor receives a personal win and seven wins ends the match',()=>{const a=arena('SOLO'),winner=a.entities[3];winner.wins=6;a.entities.forEach(e=>{if(e!==winner)e.alive=false;});a.checkRules();assert.equal(winner.wins,7);assert.equal(a.result.winner,winner.id);assert.equal(a.result.match,true);});
test('SOLO timeout selects unique highest HP + shield; ties draw',()=>{const a=arena('SOLO');a.entities.forEach(e=>{e.shield=0;});a.entities[8].shield=1;a.roundEndsAt=0;a.checkRules();assert.equal(a.result.winner,a.entities[8].id);const b=arena('SOLO');b.roundEndsAt=0;b.checkRules();assert.equal(b.result.draw,true);});
test('INFINITY respawns at four seconds and clears all movement/reload/camera/navigation state',()=>{
  const a=arena('INFINITY'),p=a.player();a.time=3;p.jumpZ=20;p.jumpV=90;p.crouching=true;p.crouchBlend=1;p.reloadLeft=1;p.recoilPitch=.5;p.cameraPitch=.7;p.ammo[0]=0;p.ai.path=[{x:0,y:0}];a.damage(p,1000,a.entities[1]);advance(a,3.975);assert.equal(p.alive,false);advance(a,.05);
  assert.equal(p.alive,true);assert.equal(p.hp,100);assert.equal(p.shield,50);for(const k of['jumpZ','jumpV','crouchBlend','reloadLeft','recoilPitch','cameraPitch'])assert.equal(p[k],0,k);assert.equal(p.crouching,false);assert.equal(p.ammo[0],30);assert.equal(a.spectatorId,null);assert.deepEqual(p.ai.path,[]);assert.ok(p.spawnProtectionUntil-a.time>1.9);
});
test('INFINITY five minute score ties draw, unique kill leader wins',()=>{for(const tie of[false,true]){const a=arena('INFINITY');a.entities[4].kills=15;a.entities[1].kills=tie?15:14;a.roundEndsAt=0;a.checkRules();assert.equal(a.result.match,true);assert.equal(a.result.draw,tie);if(!tie)assert.equal(a.result.winner,a.entities[4].id);}});
test('CAPTURE respawns at five seconds',()=>{const a=arena('CAPTURE'),p=a.player();a.damage(p,1000,a.entities[5]);advance(a,4.975);assert.equal(p.alive,false);advance(a,.05);assert.equal(p.alive,true);assert.equal(p.shield,50);});
test('BOSS is exactly 1 vs 9 and resolves either side without a time limit',()=>{const a=arena('BOSS');assert.equal(a.roundEndsAt,Infinity);a.entities.slice(1).forEach(e=>{e.alive=false;});a.checkRules();assert.equal(a.result.winner,'BOSS');const b=arena('BOSS');b.damage(b.player(),4000,b.entities[1]);b.checkRules();assert.equal(b.result.winner,'HUNTERS');assert.equal(b.result.match,true);});
test('capture accumulation pauses below two owned points and resumes at the old value',()=>{
  const a=arena('CAPTURE');a.entities.forEach(e=>{e.alive=false;});a.points[0].owner='BLUE';a.points[1].owner='BLUE';a.updateCapture(20);assert.equal(a.captureTime.BLUE,20);a.points[1].owner='RED';a.updateCapture(13);assert.equal(a.captureTime.BLUE,20);a.points[2].owner='BLUE';a.updateCapture(25);assert.equal(a.captureTime.BLUE,45);a.checkRules();assert.equal(a.result.winner,'BLUE');
});
test('capture clocks are independent and contested capture freezes progress',()=>{const a=arena('CAPTURE');a.entities.forEach(e=>{e.alive=false;});a.points[0].owner='RED';a.points[1].owner='RED';a.updateCapture(12);assert.equal(a.captureTime.RED,12);assert.equal(a.captureTime.BLUE,0);const point=a.points[2],blue=a.entities[0],red=a.entities[5];Object.assign(blue,{alive:true,x:point.x-20,y:point.y});Object.assign(red,{alive:true,x:point.x+20,y:point.y});point.control=.35;a.updateCapture(3);assert.equal(point.contested,true);assert.equal(point.control,.35);});
test('neutral capture takes five seconds and opposing ownership must be neutralized',()=>{const a=arena('CAPTURE');a.entities.forEach(e=>{e.alive=false;});const p=a.points[0],b=a.entities[0],r=a.entities[5];Object.assign(b,{alive:true,x:p.x,y:p.y});a.updateCapture(5);assert.equal(p.owner,'BLUE');b.alive=false;Object.assign(r,{alive:true,x:p.x,y:p.y});a.updateCapture(5);assert.equal(p.owner,null);a.updateCapture(5);assert.equal(p.owner,'RED');});
test('shield absorbs damage first and regens only after four seconds, bounded by each maximum',()=>{for(const mode of['TEAM','BOSS']){const a=arena(mode),p=a.player(),sh=p.maxShield;const result=a.damage(p,35,a.entities[5]);assert.equal(result.shield,35);assert.equal(result.hp,0);assert.equal(p.hp,p.maxHp);assert.equal(p.shield,sh-35);advance(a,3.975);assert.equal(p.shield,sh-35);advance(a,1.025);assert.ok(p.shield>sh-22&&p.shield<sh-18);advance(a,5);assert.equal(p.shield,sh);p.alive=false;p.shield=0;advance(a,1);assert.equal(p.shield,0);}});
test('spawn protection blocks both HP and shield damage',()=>{const a=arena('INFINITY'),p=a.player();a.damage(p,10000,a.entities[1]);assert.equal(p.hp,100);assert.equal(p.shield,50);advance(a,2.01);a.damage(p,60,a.entities[1]);assert.equal(p.shield,0);assert.equal(p.hp,90);});
test('orbs are not consumed at maximum and respect health/shield gains and respawn times',()=>{
  const a=arena('BOSS'),p=a.player();a.entities.slice(1).forEach(e=>{e.alive=false;});for(const type of ['health','shield']){const orb=a.pickups.find(p=>p.type===type);p.x=orb.x;p.y=orb.y;a.updatePickups();assert.equal(orb.active,true);if(type==='health')p.hp-=10;else p.shield-=25;a.updatePickups();assert.equal(orb.active,false);assert.equal(type==='health'?p.hp:p.shield,type==='health'?2000:1000);assert.equal(orb.respawnAt-a.time,type==='health'?9:11);p.x=a.map.boss.x;p.y=a.map.boss.y;a.time=orb.respawnAt;a.updatePickups();assert.equal(orb.active,true);}
});
test('segment-circle collision detects a target crossed entirely between frames',()=>{assert.ok(C.segmentCircle(0,0,100,0,50,0,5)>0);assert.equal(C.segmentCircle(0,30,100,30,50,0,5),null);const {a,p,t}=shootingArena();t.x=300;p.weapon=4;a.fire(p,0,0);assert.equal(a.projectiles.length,1);assert.equal(a.projectiles[0].vx,760);a.updateProjectiles(.2);assert.equal(t.shield,0);assert.equal(t.hp,40);assert.equal(a.projectiles.length,0);});
test('crossbow swept collision checks walls before farther targets',()=>{const {a,p,t}=shootingArena();a.map.grid[3][4]=1;t.x=360;p.weapon=4;a.fire(p,0,0);a.updateProjectiles(.3);assert.equal(t.hp,100);assert.equal(t.shield,50);assert.equal(a.projectiles.length,0);});
test('shotgun close hit sums eight 15-damage pellets',()=>{const {a,p,t}=shootingArena();p.weapon=3;t.x=p.x+40;const random=Math.random;Math.random=()=>.5;try{a.fire(p,0,0);}finally{Math.random=random;}assert.equal(t.shield,0);assert.equal(t.hp,30);});
test('AR and MAC continue firing while held and automatically reload',()=>{for(const id of[0,5]){const {a,p,t}=shootingArena();t.y=600;p.weapon=id;advance(a,id===0?7:11,{fire:true});assert.ok(p.shotSerial>C.WEAPONS[id].mag);}});
test('semi-auto requires a new press and independent reload durations match weapon data',()=>{const {a,p,t}=shootingArena();t.y=600;p.weapon=1;a.tick(.025,{fire:true,pressed:true});advance(a,1,{fire:true});assert.equal(p.shotSerial,1);for(const w of C.WEAPONS){if(w.id===2)continue;p.weapon=w.id;p.reloadLeft=0;p.ammo[w.id]=0;assert.equal(a.reload(p),true);assert.equal(p.reloadLeft,w.reload);}});
test('recoil decay preserves vertical freelook and NO RECOIL fully cancels MAC recoil',()=>{const {a,p}=shootingArena();p.cameraPitch=.8;p.recoilPitch=.4;advance(a,1);assert.equal(p.cameraPitch,.8);assert.ok(p.recoilPitch<.01);p.weapon=5;a.cheats.noRecoil=true;p.recoilPitch=0;p.cooldown=0;a.fire(p,0,0);assert.equal(p.recoilPitch,0);assert.equal(p.weaponKick,0);assert.equal(p.cameraPitch,.8);});
test('AIM yields to manual look and makes a bounded soft correction otherwise',()=>{const {a,p,t}=shootingArena();t.x=p.x+240;t.y=p.y+40;p.angle=0;a.aimAssist(p,1/60,{looking:true,fire:true});assert.equal(p.angle,0);a.aimAssist(p,1/60,{looking:false,fire:true});assert.ok(p.angle>0&&p.angle<.02);assert.ok(p.angle<Math.atan2(t.y-p.y,t.x-p.x));});
test('jump is a physical arc with landing and crouch changes eye/model height smoothly',()=>{const {a,p}=shootingArena();let landed=false;a.onEvent=t=>{if(t==='landing')landed=true;};a.jump(p);advance(a,.2);assert.ok(p.jumpZ>20);assert.ok(p.jumpV>0);advance(a,.7);assert.equal(p.jumpZ,0);assert.ok(landed);p.crouching=true;advance(a,.3);assert.ok(p.crouchBlend>.9);assert.ok(a.eye(p)<33);assert.ok(a.height(p)<49);});
test('safe FFA respawns avoid the candidate occupied by a living enemy',()=>{const a=arena('INFINITY'),p=a.player();for(let i=1;i<10;i++){a.entities[i].x=a.map.ffa[0].x;a.entities[i].y=a.map.ffa[0].y;}for(let i=0;i<60;i++){const spawn=a.safeSpawn(p);assert.notDeepEqual(spawn,a.map.ffa[0]);assert.ok(C.canStand(a.map,spawn.x,spawn.y,18));}});
test('spectator filters by viewpoint team in TEAM and permits everyone in FFA',()=>{const a=arena();a.player().alive=false;for(let i=0;i<10;i++){a.cycleSpectator();assert.equal(a.viewpoint().team,'BLUE');}const b=arena('SOLO');b.player().alive=false;const seen=new Set();for(let i=0;i<9;i++){b.cycleSpectator();seen.add(b.spectatorId);}assert.equal(seen.size,9);});
test('movement microsteps and frame clamp cannot tunnel through walls',()=>{const a=arena(),e=a.player();e.x=1.5*64;e.y=24.5*64;for(let i=0;i<150;i++)C.moveCircle(a.map,e,-1000,1000);assert.ok(C.canStand(a.map,e.x,e.y,18));assert.ok(e.x>=64+18);assert.ok(e.y<=26*64-18);});
test('point-blank AI notices a target behind it without auto jumping',()=>{const a=arena('SOLO',openMap()),e=a.entities[1],p=a.player();e.x=400;e.y=400;e.angle=0;p.x=330;p.y=400;a.entities.slice(2).forEach(t=>t.alive=false);C.Arena.prototype.updateAI.call(a,e,.025);assert.equal(e.ai.target,p.id);assert.equal(e.jumpZ,0);assert.equal(e.jumpV,0);});
test('all modes simulate on every map without invalid positions, NaN, or automatic AI jumping',()=>{
  for(const map of C.MAPS)for(const mode of Object.keys(C.MODES)){const a=new C.Arena();a.start(mode,map);for(let i=0;i<900;i++){a.tick(.025,{});if(i%90===0)for(const e of a.entities){assert.ok(Number.isFinite(e.x+e.y+e.angle+e.hp+e.shield),mode);assert.ok(C.canStand(map,e.x,e.y,e.radius),map.name+' '+e.name);assert.ok(e.hp>=0&&e.shield>=0);if(!e.isPlayer)assert.equal(e.jumpZ,0);}}}
});
test('Firebase adapter sends raw damage without changing remote HP/shield',()=>{const {a,p,t}=shootingArena();a.online=true;t.isRemote=true;let event;a.onEvent=(type,data)=>{if(type==='rawDamage')event=data;};a.damage(t,75,p,'AR');assert.equal(t.hp,100);assert.equal(t.shield,50);assert.equal(event.raw,75);assert.equal(event.victim,t);});
test('Firebase config accepts only public Web config and rejects service accounts',()=>{const cfg={apiKey:'public',authDomain:'test.firebaseapp.com',databaseURL:'https://test-default-rtdb.firebaseio.com',projectId:'test',appId:'test-app'};assert.equal(C.FirebaseArena.validateConfig(cfg).projectId,'test');assert.throws(()=>C.FirebaseArena.validateConfig({...cfg,private_key:'NEVER_STORE'}));assert.throws(()=>C.FirebaseArena.validateConfig({...cfg,databaseURL:'https://example.com'}));});
test('victim-side damage handling applies shield first and deduplicates network events (mock transport)',async()=>{
  const a=arena(),p=a.player(),enemy=a.entities[5];a.online=true;enemy.isRemote=true;const writes=[],net=new C.FirebaseArena(a,{status(){},notify(){},roomChanged(){}});net.code='123456';net.uid=p.id;net.members[enemy.id]={};net.shared={round:1,matchId:'test',phase:'PLAYING'};net.connected=true;net.db={};net.sdk={ref:(_db,path)=>path,set:async(ref,v)=>{writes.push([ref,v]);},remove:async()=>{},serverTimestamp:()=>Date.now()};
  const event={raw:26,weapon:'AR',attacker:enemy.id,round:1,matchId:'test',at:Date.now()};await net.receiveDamage('event1',event);assert.equal(p.hp,100);assert.equal(p.shield,24);await net.receiveDamage('event1',event);assert.equal(p.shield,24);assert.ok(writes.some(([path,v])=>path.includes('/acks/')&&v.shield===26));
});
