/* Generates the Firebase RTDB rules shipped with CHEAT ARENA. No credentials. */
'use strict';
const fs=require('node:fs'),path=require('node:path');
const room="root.child('rooms').child($room)",member=`${room}.child('members').child(auth.uid).exists()`,host=`${room}.child('meta/hostId').val() === auth.uid`;
const playing=`${room}.child('state/phase').val() === 'PLAYING'`,lobby=`${room}.child('state/phase').val() === 'LOBBY'`;
const sameRound=`newData.child('round').val() === ${room}.child('state/round').val() && newData.child('matchId').val() === ${room}.child('state/matchId').val()`;
const num=(min,max)=>({'.validate':`newData.isNumber() && newData.val() >= ${min} && newData.val() <= ${max}`});
const str=max=>({'.validate':`newData.isString() && newData.val().length <= ${max}`});
const bool={'.validate':'newData.isBoolean()'},deny={'.validate':false};
const rules={rules:{'.read':false,'.write':false,rooms:{'$room':{
  '.read':"auth !== null && $room.matches(/^[0-9]{6}$/)",
  '.write':"auth !== null && !data.exists() && newData.child('meta/hostId').val() === auth.uid && newData.child('state/phase').val() === 'LOBBY'",
  '.validate':"$room.matches(/^[0-9]{6}$/) && newData.hasChildren(['meta','state'])",
  meta:{'.validate':"newData.hasChildren(['hostId','createdAt','schema','mode'])",hostId:{'.write':`auth !== null && ${member} && newData.val() === auth.uid && (!data.exists() || !${room}.child('members').child(data.val()).exists() || data.val() === auth.uid)`,...str(128)},createdAt:num(0,9999999999999),schema:{'.validate':'newData.val() === 2'},mode:{'.validate':"newData.val() === 'RANDOM'"},'$other':deny},
  seats:{'$seat':{'.write':`auth !== null && ((!data.exists() && ${lobby} && newData.child('uid').val() === auth.uid) || (!newData.exists() && data.child('uid').val() === auth.uid))`,'.validate':"$seat.matches(/^[0-9]$/) && newData.hasChildren(['uid','joinedAt'])",uid:str(128),joinedAt:num(0,9999999999999),'$other':deny}},
  members:{'$uid':{'.write':`auth !== null && auth.uid === $uid && (!newData.exists() || (${lobby} && ${room}.child('seats').child(newData.child('slot').val()).child('uid').val() === auth.uid))`,'.validate':"newData.hasChildren(['nickname','slot','joinedAt'])",nickname:{'.validate':'newData.isString() && newData.val().length > 0 && newData.val().length <= 18'},slot:{'.validate':"newData.isString() && newData.val().matches(/^[0-9]$/)"},joinedAt:num(0,9999999999999),'$other':deny}},
  roster:{'.write':`auth !== null && ${member} && ${host}`,'$uid':{'.validate':"newData.hasChildren(['nickname','team','spawnIndex'])",nickname:str(18),team:{'.validate':"newData.val() === 'BLUE' || newData.val() === 'RED' || newData.val() === 'SOLO' || newData.val() === 'BOSS' || newData.val() === 'HUNTERS'"},spawnIndex:num(0,9),matchId:str(100),'$other':deny}},
  state:{'.write':`auth !== null && ${member} && ${host}`,'.validate':"newData.hasChildren(['phase','mode','round','score','mapId'])",phase:{'.validate':"newData.val() === 'LOBBY' || newData.val() === 'PLAYING' || newData.val() === 'ROUND_END' || newData.val() === 'MATCH_END'"},mode:{'.validate':"newData.val() === 'TEAM' || newData.val() === 'SOLO' || newData.val() === 'INFINITY' || newData.val() === 'BOSS' || newData.val() === 'CAPTURE'"},round:num(0,9999),mapId:{'.validate':"newData.val() === 'depot' || newData.val() === 'cargo' || newData.val() === 'lab' || newData.val() === 'plaza'"},matchId:str(100),roundStartedAt:num(0,9999999999999),roundEndsAt:num(0,9999999999999),transitionAt:num(0,9999999999999),score:{'$id':num(0,7)},captureTime:{BLUE:num(0,45),RED:num(0,45),'$other':deny},captureUpdatedAt:num(0,9999999999999),points:{'$id':{'.validate':"$id === 'A' || $id === 'B' || $id === 'C'",owner:{'.validate':"newData.val() === 'BLUE' || newData.val() === 'RED'"},control:num(-1,1),contested:bool,capturing:{'.validate':"newData.val() === 'BLUE' || newData.val() === 'RED'"},'$other':deny}},result:{winner:str(128),name:str(128),draw:bool,reason:str(200),match:bool,'$other':deny},'$other':deny},
  players:{'$uid':{'.write':`auth !== null && auth.uid === $uid && (!newData.exists() || (${member} && ${room}.child('roster').child(auth.uid).exists() && ${playing} && ${sameRound}))`,'.validate':"newData.hasChildren(['x','y','angle','cameraPitch','hp','shield','alive','weapon','round','matchId','updatedAt']) && ((newData.child('hp').val() > 0 && newData.child('alive').val() === true) || (newData.child('hp').val() === 0 && newData.child('alive').val() === false))",
    x:num(18,1902),y:num(18,1710),angle:num(-6.4,6.4),cameraPitch:num(-1.12,1.12),recoilPitch:num(0,.6),hp:{'.validate':`newData.isNumber() && newData.val() >= 0 && newData.val() <= (${room}.child('roster').child($uid).child('team').val() === 'BOSS' ? 2000 : 100)`},shield:{'.validate':`newData.isNumber() && newData.val() >= 0 && newData.val() <= (${room}.child('roster').child($uid).child('team').val() === 'BOSS' ? 1000 : 50)`},life:num(0,999999),respawnEndsAt:num(0,9999999999999),protectionEndsAt:num(0,9999999999999),alive:bool,weapon:num(0,5),jumpZ:num(0,65),jumpV:num(-400,300),crouching:bool,crouchBlend:num(0,1),vx:num(-300,300),vy:num(-300,300),walkPhase:num(0,99999999),moveSpeed:num(0,1000),ammo:num(-1,80),reloadLeft:num(0,4.2),reloadTotal:num(0,4.2),shotSerial:num(0,9999999),kills:num(0,9999999),deaths:num(0,9999999),round:num(1,9999),matchId:str(100),updatedAt:{'.validate':'newData.isNumber() && newData.val() <= now + 2000'},lastShot:{angle:num(-7,7),pitch:num(-2,2),x:num(18,1902),y:num(18,1710),z:num(0,120),at:num(0,9999999999999),'$other':deny},'$other':deny}},
  damage:{'$victim':{'$event':{'.write':`auth !== null && ((!newData.exists() && auth.uid === $victim) || (!data.exists() && ${member} && auth.uid !== $victim && ${room}.child('members').child($victim).exists() && newData.child('attacker').val() === auth.uid && ${room}.child('players').child(auth.uid).child('alive').val() === true && ${playing} && ${sameRound}))`,'.validate':"newData.hasChildren(['attacker','raw','weapon','round','matchId','at'])",attacker:str(128),life:num(0,999999),raw:num(.001,120),weapon:{'.validate':"newData.isString() && newData.val().matches(/^(AR|PISTOL|KNIFE|SHOTGUN|CROSSBOW|MAC)$/)"},round:num(1,9999),matchId:str(100),at:{'.validate':'newData.isNumber() && newData.val() <= now + 1000 && newData.val() >= now - 5000'},'$other':deny}}},
  acks:{'$attacker':{'$event':{'.write':`auth !== null && ((!newData.exists() && auth.uid === $attacker) || (!data.exists() && ${member} && newData.child('victim').val() === auth.uid && ${room}.child('damage').child(auth.uid).child($event).child('attacker').val() === $attacker))`,'.validate':"newData.hasChildren(['victim','hp','shield','round','matchId','at']) && newData.child('hp').val() + newData.child('shield').val() <= 120",victim:str(128),hp:num(0,120),shield:num(0,120),round:num(1,9999),matchId:str(100),at:num(0,9999999999999),'$other':deny}}},
  kills:{'.write':`auth !== null && ${host} && ${member} && !newData.exists()`,'$kill':{'.write':`auth !== null && ${member} && !data.exists() && newData.child('victimId').val() === auth.uid && ${sameRound}`,'.validate':"newData.hasChildren(['attackerId','attacker','victimId','victim','weapon','round','matchId','at'])",attackerId:str(128),attacker:str(18),victimId:str(128),victim:str(18),weapon:str(16),round:num(1,9999),matchId:str(100),at:num(0,9999999999999),'$other':deny}},
  pickups:{'.write':`auth !== null && ${host} && ${member}`,'$pickup':{'.validate':"$pickup.matches(/^orb-[0-5]$/) && newData.hasChildren(['active','respawnAt','round','matchId','type','x','y'])",active:bool,respawnAt:num(0,9999999999999),round:num(1,9999),matchId:str(100),type:{'.validate':"newData.val() === 'health' || newData.val() === 'shield'"},x:num(64,1856),y:num(64,1664),claimUid:str(128),grantId:str(240),'$other':deny}},
  pickupRequests:{'$uid':{'.write':`auth !== null && ((auth.uid === $uid && (!newData.exists() || (${member} && ${playing} && ${sameRound}))) || (${host} && !newData.exists()))`,'.validate':"newData.hasChildren(['pickupId','round','matchId','at'])",pickupId:{'.validate':"newData.isString() && newData.val().matches(/^orb-[0-5]$/)"},round:num(1,9999),matchId:str(100),at:num(0,9999999999999),'$other':deny}},
  '$other':deny
}}}};
fs.writeFileSync(path.join(__dirname,'../dist/database.rules.json'),JSON.stringify(rules,null,2)+'\n');
console.log('Generated dist/database.rules.json');
